SHRINKWRAP-190 Catch NoClassDefFoundError during addPackage and convert it to a RuntimeException with information about which class was loaded that caused the issue. Original exception set as Exception cause.